// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/analytics/challenge/{challengeId}": {
            "get": {
                "description": "Obtiene todos los análisis de ejecuciones de un challenge específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Obtener analytics por ID de challenge",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del challenge",
                        "name": "challengeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Tamaño de página",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/date-range": {
            "get": {
                "description": "Obtiene todos los análisis de ejecuciones en un rango de fechas específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Obtener analytics por rango de fechas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fecha de inicio (RFC3339)",
                        "name": "startDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fecha de fin (RFC3339)",
                        "name": "endDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Tamaño de página",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/execution/{executionId}": {
            "get": {
                "description": "Obtiene el análisis completo de una ejecución específica por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Obtener analytics por ID de ejecución",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la ejecución",
                        "name": "executionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/kpi/challenge/{challengeId}": {
            "get": {
                "description": "Obtiene las métricas clave de rendimiento de un challenge específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KPI"
                ],
                "summary": "Obtener KPIs de un challenge",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del challenge",
                        "name": "challengeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/kpi/daily": {
            "get": {
                "description": "Obtiene las métricas agregadas por día",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KPI"
                ],
                "summary": "Obtener KPIs diarios",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 30,
                        "description": "Límite de resultados",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/kpi/languages": {
            "get": {
                "description": "Obtiene las métricas agregadas por lenguaje de programación",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KPI"
                ],
                "summary": "Obtener KPIs por lenguaje de programación",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/kpi/student/{studentId}": {
            "get": {
                "description": "Obtiene las métricas clave de rendimiento de un estudiante específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KPI"
                ],
                "summary": "Obtener KPIs de un estudiante",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del estudiante",
                        "name": "studentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/kpi/top-failed-challenges": {
            "get": {
                "description": "Obtiene los challenges que tienen mayor cantidad de ejecuciones fallidas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KPI"
                ],
                "summary": "Obtener top challenges con más fallos",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Límite de resultados",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/student/{studentId}": {
            "get": {
                "description": "Obtiene todos los análisis de ejecuciones de un estudiante específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Obtener analytics por ID de estudiante",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del estudiante",
                        "name": "studentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Tamaño de página",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sync/events": {
            "post": {
                "description": "Obtiene todos los eventos del tópico execution.analytics de Kafka y los guarda en la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sync"
                ],
                "summary": "Sincronizar eventos de Kafka",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-registration-analytics/all": {
            "get": {
                "description": "Obtiene todos los registros de usuarios con paginación",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Registration Analytics"
                ],
                "summary": "Obtener todos los registros de usuarios",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Límite de resultados",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset para paginación",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de todos los registros",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-registration-analytics/date-range": {
            "get": {
                "description": "Obtiene todos los registros de usuarios en un rango de fechas específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Registration Analytics"
                ],
                "summary": "Obtener registros por rango de fechas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fecha de inicio (RFC3339, ej: 2024-01-01T00:00:00Z)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fecha de fin (RFC3339, ej: 2024-12-31T23:59:59Z)",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Límite de resultados",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset para paginación",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de registros en el rango de fechas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-registration-analytics/email/{email}": {
            "get": {
                "description": "Obtiene el análisis de registro de un usuario por su email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Registration Analytics"
                ],
                "summary": "Obtener analytics por email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email del usuario",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Datos del registro del usuario",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Usuario no encontrado",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-registration-analytics/kpi/daily-registrations": {
            "get": {
                "description": "Obtiene estadísticas de registros de usuarios agrupadas por día",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Registration Analytics"
                ],
                "summary": "Obtener estadísticas diarias de registros",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fecha de inicio (RFC3339, ej: 2024-01-01T00:00:00Z)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fecha de fin (RFC3339, ej: 2024-12-31T23:59:59Z)",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Estadísticas diarias",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/repositories.DailyRegistrationStats"
                            }
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-registration-analytics/kpi/provider-stats": {
            "get": {
                "description": "Obtiene estadísticas de usuarios registrados agrupados por proveedor (google, facebook, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Registration Analytics"
                ],
                "summary": "Obtener estadísticas por proveedor",
                "responses": {
                    "200": {
                        "description": "Estadísticas por proveedor",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/repositories.ProviderStats"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-registration-analytics/kpi/top-email-domains": {
            "get": {
                "description": "Obtiene los dominios de email más usados en los registros de usuarios",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Registration Analytics"
                ],
                "summary": "Obtener los dominios de email más usados",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Límite de resultados",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Top dominios de email",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/repositories.EmailDomainStats"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-registration-analytics/kpi/total-users": {
            "get": {
                "description": "Obtiene el número total de usuarios registrados en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Registration Analytics"
                ],
                "summary": "Obtener total de usuarios registrados",
                "responses": {
                    "200": {
                        "description": "Total de usuarios",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-registration-analytics/provider/{provider}": {
            "get": {
                "description": "Obtiene todos los usuarios registrados con un proveedor específico (google, facebook, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Registration Analytics"
                ],
                "summary": "Obtener usuarios por proveedor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Proveedor (google, facebook, github, twitter, local, apple, microsoft)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Límite de resultados",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset para paginación",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de usuarios registrados",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-registration-analytics/sync": {
            "post": {
                "description": "Lee todos los mensajes disponibles del tópico iam.user.registered y los guarda en la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Registration Analytics"
                ],
                "summary": "Sincronizar eventos de registro de usuarios desde Kafka",
                "responses": {
                    "200": {
                        "description": "Resultado de la sincronización",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-registration-analytics/user/{userId}": {
            "get": {
                "description": "Obtiene el análisis de registro de un usuario específico por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Registration Analytics"
                ],
                "summary": "Obtener analytics por ID de usuario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del usuario (UUID)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Datos del registro del usuario",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Usuario no encontrado",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "repositories.DailyRegistrationStats": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "localRegistrations": {
                    "type": "integer",
                    "format": "int64"
                },
                "oauthRegistrations": {
                    "type": "integer",
                    "format": "int64"
                },
                "totalRegistrations": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
        "repositories.EmailDomainStats": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "percentage": {
                    "type": "number",
                    "format": "float64"
                },
                "totalUsers": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
        "repositories.ProviderStats": {
            "type": "object",
            "properties": {
                "percentageUsed": {
                    "type": "number",
                    "format": "float64"
                },
                "provider": {
                    "type": "string"
                },
                "totalUsers": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "100.102.208.55:8291",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Analytics Microservice API",
	Description:      "Microservicio de análisis de ejecuciones de código con arquitectura DDD",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
